baseURL = 'https://runshell.github.io/'
languageCode = 'zh-CN'
title = 'runshell'
theme = 'stack'



features = [
    "disqus",
    "photoswipe",
    "opengraph",
    "widgets",
    "darkmode",
    "table of contents",
    "search",
]


[Params]
    [Params.Sidebar]
        emoji = "ğŸ¤£"
        subtitle = "Dream is possible!"
        [Params.Sidebar.avatar]
            enabled = true
            local = true
            src = "img/avatar.png"
    [Params.Article]
        toc = true
    [Params.Footer]
        since = 2018
        customText = "runshell"
    [Params.Search]
        enable = true
        type = "json"
        contentLength = 5000  # ç´¢å¼•å†…å®¹é•¿åº¦
        mainSections = ["post"]
        
    [Params.widgets]
        [[Params.widgets.homepage]]
            type = "search"
            params = {placeholder = "æœç´¢æ–‡ç« ...",searchJsonUrl = "/search.json"}
        [[Params.widgets.homepage]]
            type = "archives"
            params = {}
        [[Params.widgets.homepage]]
            type = "categories"
            params = {}
        [[Params.widgets.homepage]]
            type = "tag-cloud"
            params = {}
        [[Params.widgets.page]]
            type = "toc"
            params = {}

[menu]
[[menu.main]]
[[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/runshell"
    [menu.social.params]
        icon = "brand-github"
